import json, ast, hashlib
from typing import Any, List, Dict
from datetime import datetime

# Contract observations are stored per function per session
# Structure: { "filePath:functionName": [{ inputs, output, timestamp, isEdgeCase, inputHash }] }
observations: Dict[str, List] = {}

def record_observation(file_path: str, function_name: str, inputs: list, output: Any, error: str = None):
    key = f"{file_path}:{function_name}"
    if key not in observations:
        observations[key] = []

    # Detect edge cases: None/null inputs, empty collections, zero values, error outputs
    is_edge = (
        any(v is None for v in inputs) or
        any(v == [] or v == {} or v == "" for v in inputs) or
        any(v == 0 for v in inputs) or
        error is not None
    )

    # Simplified hash for comparison
    try:
        input_str = json.dumps(inputs, default=str)
    except Exception:
        input_str = str(inputs)
    
    input_hash = hashlib.md5(input_str.encode()).hexdigest()[:8]

    # Deduplicate: don't store same inputs twice
    existing_hashes = {o['inputHash'] for o in observations[key]}
    if input_hash not in existing_hashes:
        observations[key].append({
            "inputs": inputs,
            "output": output,
            "error": error,
            "timestamp": datetime.utcnow().isoformat(),
            "isEdgeCase": is_edge,
            "inputHash": input_hash
        })

def generate_snapshot_tests(file_path: str, function_name: str, language: str) -> str:
    key = f"{file_path}:{function_name}"
    obs_list = observations.get(key, [])
    if not obs_list:
        from pathlib import Path
        stem = Path(file_path).stem
        if language == 'python':
            return f"""# Auto-generated by Aeres IDE — Contract Snapshot Tests
import pytest
from {stem} import {function_name}  # adjust path as needed

class Test{function_name.title().replace('_','')}Contract:
    def test_proposed_call_0(self):
        # TODO: Add your input arguments here
        result = {function_name}()
        assert result is not None
"""
        else:
            return f"""// Auto-generated by Aeres IDE — Contract Snapshot Tests
import {{ {function_name} }} from '../{stem}'  // adjust path as needed

describe('{function_name} contract snapshots', () => {{
  it('proposed call 0', () => {{
    // TODO: Add your input arguments here
    const result = {function_name}()
    expect(result).toBeDefined()
  }})
}})
"""

    if language == 'python':
        return _generate_python_tests(function_name, file_path, obs_list)
    elif language in ('javascript', 'typescript'):
        return _generate_js_tests(function_name, file_path, obs_list, language)
    return ""

def _generate_python_tests(fn: str, file_path: str, obs: List) -> str:
    mod_name = Path(file_path).stem
    lines = [
        f"# Auto-generated by Aeres IDE — Contract Snapshot Tests",
        f"# Generated from {len(obs)} observed calls to {fn}()",
        f"import pytest",
        f"from {mod_name} import {fn}  # adjust path as needed",
        f"",
        f"class Test{fn.title().replace('_','')}Contract:",
    ]
    for i, o in enumerate(obs[:20]):
        label = f"edge_case_{i}" if o['isEdgeCase'] else f"observed_call_{i}"
        args = ', '.join(repr(v) for v in o['inputs'])
        if o['error']:
            lines += [
                f"",
                f"    def test_{label}(self):",
                f"        # Observed: {o['error']}",
                f"        with pytest.raises(Exception):",
                f"            {fn}({args})",
            ]
        else:
            lines += [
                f"",
                f"    def test_{label}(self):",
                f"        result = {fn}({args})",
                f"        assert result == {repr(o['output'])}",
            ]
    return '\n'.join(lines)

def _generate_js_tests(fn: str, file_path: str, obs: List, lang: str) -> str:
    mod_name = Path(file_path).stem
    lines = [
        f"// Auto-generated by Aeres IDE — Contract Snapshot Tests",
        f"// Generated from {len(obs)} observed calls to {fn}()",
        f"import {{ {fn} }} from '../{mod_name}'  // adjust path as needed",
        f"",
        f"describe('{fn} contract snapshots', () => {{",
    ]
    for i, o in enumerate(obs[:20]):
        label = f"edge case {i}" if o['isEdgeCase'] else f"observed call {i}"
        args = ', '.join(json.dumps(v, default=str) for v in o['inputs'])
        if o['error']:
            lines += [
                f"",
                f"  it('{label} (throws)', () => {{",
                f"    expect(() => {fn}({args})).toThrow()",
                f"  }})",
            ]
        else:
            lines += [
                f"",
                f"  it('{label}', () => {{",
                f"    expect({fn}({args})).toEqual({json.dumps(o['output'], default=str)})",
                f"  }})",
            ]
    lines.append('})')
    return '\n'.join(lines)
from pathlib import Path
