import React, { useState, useEffect } from 'react'
import { useStore } from '../../store.js'

export default function ContractSnapshot() {
  const activeTabId = useStore((s) => s.activeTabId)
  const tabs = useStore((s) => s.tabs)
  const activeTab = tabs.find(t => t.id === activeTabId)
  const [summary, setSummary] = useState([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(null) // function name
  const [offline, setOffline] = useState(false)

  async function fetchSummary() {
    if (!activeTab || !window.electron) return
    setLoading(true)
    try {
      const res = await window.electron.analyze.contractSummary(activeTab.path)
      if (res?.error) {
        setOffline(true)
      } else {
        setSummary(Array.isArray(res) ? res : [])
        setOffline(false)
      }
    } catch (err) {
      console.error(err)
      setOffline(true)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchSummary()
    const int = setInterval(fetchSummary, 5000)
    return () => clearInterval(int)
  }, [activeTab?.path])

  async function handleGenerate(fn) {
    if (!activeTab) return
    setGenerating(fn)
    try {
      let testCode = null

      // Try backend first
      if (window.electron?.analyze?.contractGenerate) {
        try {
          const json = await window.electron.analyze.contractGenerate({
            file_path: activeTab.path,
            function_name: fn,
            language: activeTab.language
          })
          if (json?.tests && !json.error) {
            testCode = json.tests
          }
        } catch { /* backend offline, fall through to local generation */ }
      }

      // LLM Smart Fallback: If no runtime observations exist, generate highly realistic test mock data
      if (!testCode || testCode.includes('TODO: Add your input arguments here')) {
        try {
          if (window.electron?.rag?.query) {
            let prompt = `You are an expert testing agent. Generate a robust unit test for the function '${fn}' based on its signature in the following code. Provide highly REALISTIC mock data and edge case payloads. Return ONLY the raw test code inside a markdown code block, with no explanations or introductory text.

CRITICAL REQUIREMENT FOR COMPILATION:
You MUST generate 100% complete, fully compiling test code with all required test frameworks and imports included at the top:
- For Python: Include 'import pytest' and the correct import from your module (e.g. 'from ${baseName} import ${fn}').
- For Go: Prepend 'package main' and 'import (\n\t"testing"\n)' and write standard 'Test...' function with 't *testing.T'.
- For Rust: Include standard unit test modules 'mod tests' with 'use super::*;' and '#[test]' annotations.
- For Java: Include JUnit 5 imports like 'import org.junit.jupiter.api.Test;' and static assertion imports.
- For C++: Include '#include <gtest/gtest.h>' or standard assert headers.
- For C#: Include standard 'using Xunit;' namespace.
- For React/JSX/TSX: Include 'import React from "react"', 'import { render, fireEvent } from "@testing-library/react"', and 'import "@testing-library/jest-dom"'.

Ensure the test file compiles immediately and contains no placeholders; generate working code.`
            const res = await window.electron.rag.query(prompt, activeTab.content)
            if (res && res.answer && !res.answer.toLowerCase().includes('error')) {
              const match = res.answer.match(/```[\w]*\n([\s\S]*?)```/)
              if (match && match[1]) {
                testCode = match[1].trim()
              } else {
                testCode = res.answer.replace(/```[\w]*\n?/g, '').replace(/```/g, '').trim()
              }
              // Prepend header
              const commentPrefix = activeTab.language === 'python' ? '#' : '//'
              testCode = `${commentPrefix} Auto-generated by Aeres AI — Smart Static Analysis Mock\n${testCode}`
            }
          }
        } catch (e) { console.error('LLM generation failed', e) }
      }

      // Local fallback: generate test scaffold directly in the client if LLM fails
      if (!testCode || testCode.includes('TODO: Add your input arguments here')) {
        const lang = activeTab.language || 'javascript'
        const stem = activeTab.name.replace(/\.[^/.]+$/, '')
        // Fixed: declare baseName and isReact BEFORE they are used in templates below
        const baseName = stem
        const isReact = activeTab.content?.includes('React') || activeTab.content?.includes('export default') || activeTab.name.endsWith('x') || activeTab.name.includes('page') || activeTab.name.includes('layout');
        
        if (lang === 'python') {
          testCode = `# Auto-generated by Aeres IDE — Contract Snapshot Tests
import pytest
from ${stem} import ${fn}  # adjust import path as needed

class Test${fn.charAt(0).toUpperCase() + fn.slice(1).replace(/_(\w)/g, (_, c) => c.toUpperCase())}Contract:
    """Snapshot tests for ${fn}() — generated from static analysis."""

    def test_basic_call(self):
        """Verify ${fn} returns a non-None result with default args."""
        result = ${fn}()
        assert result is not None

    def test_edge_case_none_input(self):
        """Edge case: passing None should be handled gracefully."""
        try:
            result = ${fn}(None)
        except (TypeError, ValueError):
            pass  # Expected — function rejects None

    def test_edge_case_empty(self):
        """Edge case: passing empty values."""
        try:
            result = ${fn}("")
        except (TypeError, ValueError):
            pass  # Expected
`
        } else if (isReact) {
          testCode = `// Auto-generated by Aeres IDE — React Component Unit Tests
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import ${baseName} from './${baseName}'  // adjust import path as needed

describe('${baseName} Component', () => {
  it('should render correctly with default props', () => {
    const { container } = render(<${baseName} />)
    expect(container).toBeInTheDocument()
  })

  it('should support interacting with the component', () => {
    const { container } = render(<${baseName} />)
    const buttons = container.querySelectorAll('button')
    if (buttons.length > 0) {
      fireEvent.click(buttons[0])
    }
  })
})
`
        } else if (lang === 'go') {
          testCode = `package main

import (
	"testing"
)

// Auto-generated by Aeres IDE — Go Snapshot Tests for ${fn}
func Test${fn.charAt(0).toUpperCase() + fn.slice(1)}(t *testing.T) {
	t.Run("basic call", func(t *testing.T) {
		// TODO: call the function and assert results
		t.Log("Testing basic call for ${fn}")
	})
}
`
        } else if (lang === 'rust') {
          testCode = `// Auto-generated by Aeres IDE — Rust Snapshot Tests for ${fn}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_${fn.toLowerCase()}() {
        // TODO: call ${fn}() and assert
        assert!(true);
    }
}
`
        } else if (lang === 'java') {
          testCode = `// Auto-generated by Aeres IDE — Java JUnit Tests for ${fn}
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ${stem}Test {
    @Test
    public void test${fn.charAt(0).toUpperCase() + fn.slice(1)}() {
        // TODO: Instantiate class and test ${fn}()
        assertTrue(true);
    }
}
`
        } else if (lang === 'csharp') {
          testCode = `// Auto-generated by Aeres IDE — C# xUnit Tests for ${fn}
using System;
using Xunit;

public class ${stem}Tests
{
    [Fact]
    public void Test_${fn}()
    {
        // TODO: Call your method and verify
        Assert.True(true);
    }
}
`
        } else if (lang === 'cpp' || lang === 'c') {
          testCode = `// Auto-generated by Aeres IDE — C++ Google Test for ${fn}
#include <gtest/gtest.h>

TEST(${stem}Test, Test_${fn}) {
    // TODO: Write assertions here
    SUCCEED();
}
`
        } else {
          testCode = `// Auto-generated by Aeres IDE — Contract Snapshot Tests
import { ${fn} } from './${stem}'  // adjust import path as needed

describe('${fn} contract snapshots', () => {
  it('should return a defined result with default args', () => {
    const result = ${fn}()
    expect(result).toBeDefined()
  })

  it('should handle null input gracefully', () => {
    expect(() => ${fn}(null)).not.toThrow()
  })

  it('should handle empty string input', () => {
    expect(() => ${fn}('')).not.toThrow()
  })

  it('should handle edge case: zero', () => {
    const result = ${fn}(0)
    expect(result).toBeDefined()
  })
})
`
        }
      }

      // Derive the test file name from language conventions
      // (baseName and lang already declared in the local fallback block above; re-derive here for safety)
      const baseName = activeTab.name.replace(/\.[^/.]+$/, '')
      const lang = activeTab.language || 'javascript'
      
      let testFileName = `${baseName}.test.js`
      if (lang === 'python') testFileName = `test_${baseName}.py`
      else if (lang === 'go') testFileName = `${baseName}_test.go`
      else if (lang === 'rust') testFileName = `${baseName}_test.rs`
      else if (lang === 'java') testFileName = `${baseName}Test.java`
      else if (lang === 'kotlin') testFileName = `${baseName}Test.kt`
      else if (lang === 'cpp' || lang === 'c') testFileName = `test_${baseName}.cpp`
      else if (lang === 'ruby') testFileName = `${baseName}_spec.rb`
      else if (lang === 'php') testFileName = `${baseName}Test.php`
      else if (lang === 'csharp') testFileName = `${baseName}Tests.cs`
      else if (lang === 'typescript' || lang === 'typescriptreact') {
        const isReact = activeTab.content?.includes('React') || activeTab.content?.includes('export default') || activeTab.name.endsWith('x') || activeTab.name.includes('page') || activeTab.name.includes('layout');
        testFileName = isReact ? `${baseName}.test.tsx` : `${baseName}.test.ts`
      } else if (lang === 'javascript' || lang === 'javascriptreact') {
        const isReact = activeTab.content?.includes('React') || activeTab.content?.includes('export default') || activeTab.name.endsWith('x') || activeTab.name.includes('page') || activeTab.name.includes('layout');
        testFileName = isReact ? `${baseName}.test.jsx` : `${baseName}.test.js`
      }

      const testFilePath = activeTab.path.replace(activeTab.name, testFileName)

      // Automatically save to the filesystem so it appears in the Explorer
      if (window.electron?.fs?.writeFile) {
        await window.electron.fs.writeFile(testFilePath, testCode)
      }

      // Resolve proper Monaco syntax highlight language for the test file
      let editorLanguage = activeTab.language || 'javascript'
      const ext = testFileName.split('.').pop()
      if (ext === 'js' || ext === 'jsx') editorLanguage = 'javascript'
      else if (ext === 'ts' || ext === 'tsx') editorLanguage = 'typescript'
      else if (ext === 'py') editorLanguage = 'python'
      else if (ext === 'go') editorLanguage = 'go'
      else if (ext === 'rs') editorLanguage = 'rust'
      else if (ext === 'cs') editorLanguage = 'csharp'
      else if (ext === 'java') editorLanguage = 'java'
      else if (ext === 'kt') editorLanguage = 'kotlin'
      else if (ext === 'rb') editorLanguage = 'ruby'
      else if (ext === 'php') editorLanguage = 'php'
      else if (ext === 'cpp' || ext === 'c' || ext === 'h' || ext === 'hpp') editorLanguage = 'cpp'

      // Open a new editor tab with the generated snapshot test
      const store = useStore.getState()
      store.openTab({
        name: testFileName,
        path: testFilePath,
        content: testCode,
        language: editorLanguage,
        isDirty: false
      })
      // Switch view back to the editor canvas so user sees the generated file
      document.dispatchEvent(new CustomEvent('aeres:open-explorer'))
    } catch (err) {
      console.error('[ContractSnapshot] Generate failed:', err)
      alert(`Failed to generate snapshot test: ${err.message}`)
    } finally {
      setGenerating(null)
    }
  }

  if (!activeTab) return (
    <div className="p-8 text-center text-aeres-muted text-sm">Open a file to see observed behaviors.</div>
  )

  return (
    <div className="flex flex-col h-full bg-aeres-bg">
      <div className="p-3 border-b border-aeres-border flex justify-between items-center">
        <h3 className="text-xs font-bold text-white uppercase tracking-wider">Contract Snapshots</h3>
        <button onClick={fetchSummary} className="p-1 hover:text-white transition-colors text-aeres-muted">
          <svg className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
        </button>
      </div>

      {offline && (
        <div className="mx-2 my-2 p-3 rounded-lg border border-yellow-800/40 bg-yellow-950/20 text-yellow-500 text-[11px] leading-relaxed animate-in slide-in-from-top-1 duration-200">
          <div className="flex gap-2">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="shrink-0 mt-0.5"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
            <div>
              <span className="font-bold block mb-0.5">Observer Offline</span>
              Deep contract inspection sidecar is unreachable. Please verify backend is running on settings port.
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 overflow-y-auto">
        {loading && summary.length === 0 ? (
          <div className="p-12 flex flex-col items-center justify-center space-y-3">
             <div className="w-8 h-8 rounded-full border-2 border-aeres-violet border-t-transparent animate-spin" />
             <span className="text-[10px] text-aeres-muted animate-pulse uppercase font-bold tracking-widest">Watching runtime artifacts...</span>
          </div>
        ) : summary.length === 0 ? (
          <div className="p-8 text-center text-aeres-muted text-xs">
            No observations yet. Run or debug your code to capture runtime behavior.
          </div>
        ) : (
          <div className="p-2 space-y-2">
            {summary.map(s => (
              <div key={s.function} className="p-3 rounded-lg border border-aeres-border bg-aeres-surface/40 group hover:border-aeres-violet/50 transition-colors">
                <div className="flex justify-between items-start mb-2">
                  <span className="text-xs font-mono text-white truncate max-w-[150px]" title={s.function}>{s.function}</span>
                  <div className="flex flex-col items-end gap-1">
                    {s.callCount === 0 ? (
                      <span className="text-[9px] font-bold tracking-wider bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded leading-none border border-slate-700/50">STATIC ANALYSIS</span>
                    ) : (
                      <span className="text-[10px] bg-aeres-violet/20 text-aeres-violet px-1.5 py-0.5 rounded leading-none">{s.callCount} calls observed</span>
                    )}
                    {s.edgeCases > 0 && <span className="text-[10px] bg-aeres-amber/20 text-aeres-amber px-1.5 py-0.5 rounded leading-none">{s.edgeCases} runtime edges</span>}
                  </div>
                </div>
                <button
                  onClick={() => handleGenerate(s.function)}
                  disabled={generating === s.function}
                  className="w-full py-1.5 text-[10px] font-bold uppercase tracking-wider bg-aeres-border hover:bg-aeres-violet text-white transition-colors rounded shadow-sm disabled:opacity-50"
                >
                  {generating === s.function ? 'Generating...' : 'Generate Snapshot Test'}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="p-3 bg-aeres-violet/5 border-t border-aeres-violet/20">
        <p className="text-[10px] text-aeres-violet/80 leading-relaxed italic">
          Aeres IDE anchors your code to reality by watching its true behavior at runtime, shielding you from assumption-based regressions.
        </p>
      </div>
    </div>
  )
}
